[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build -t app ."

[deploy]
startCommand = "gunicorn --workers 2 --threads 4 --timeout 60 --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production" 