services:
  - type: web
    name: pdf-converter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential libgl1-mesa-glx libglib2.0-0 python3-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DEPLOYMENT_VERSION
        value: "1.0.1"
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
    healthCheckPath: /health
    healthCheckTimeout: 300
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate, proxy-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0" 