services:
  - type: web
    name: pdf-converter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PATH
        value: "/usr/local/bin:/usr/bin:/bin"
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1 