services:
  - type: web
    name: pdf-converter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential libgl1-mesa-glx libglib2.0-0 python3-dev
      pip install --upgrade pip
      pip install setuptools wheel
      pip install numpy==1.24.3
      pip install fire==0.5.0 python-fire==0.5.0
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1 